config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations'}, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  get '/health-check/' => 'auth#sign_in'
  resources :users

  mount ReportsKit::Engine, at: '/'

  resources :customers
  get 'qbwc/action' => 'qbwc#_generate_wsdl'
  get 'qbwc/qwc' => 'qbwc#qwc'
  wash_out :qbwc

  constraints defaults: { format: :json } do
    match '/:webhook_token' => 'welcome#api', as: :subscription_webhook, via: [:options, :post]
  end
  

  root :to => 'users#homepages'

  get 'qbwc_settings' => 'users#qbwc_settings'
  put 'qbwc_enabled' => 'users#qbwc_enabled'
  put 'qb_helper' => 'users#qb_helper'

  get :search, controller: :dashboard
    
  resources :orders do resources :comments end

  resources :orders
  resources :items
  resources :sites
  resources :site_inventories
  resources :bills
  resources :trackings
  resources :invoices
  resources :accounts
  resources :credit_memos
  resources :reports
  resources :fulfillment
  
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  get '/email_send' => 'trackings#email_send'
    
  get '/customer_details' => 'orders#customer_details'

  get '/dashboard' => 'dashboard#index'
  get '/dashboard/consumer' => 'dashboard#consumer'
  
    

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_action :authenticate_user!
	helper_method :sort_column, :sort_direction, :classed_remove
	before_filter :dash_variables

	
	def dash_variables
		# Reused Variables -> just in this controller
		@t_now = Time.now
		@beg_month = @t_now.beginning_of_month
		@end_month = @t_now.end_of_month
		@gs_account_id = "items.account_id = 152"
		@prev_beg_month = 1.year.ago.beginning_of_month
		@prev_end_month = 1.year.ago.end_of_month
		@prev_td_month = 1.year.ago.to_date
		@homecurrency = "line_items.homecurrency_amount"
		@account_amount = "account_line_items.amount"
		@account_array = ["account_line_items.account_type = ? and account_line_items.account_id = ?", "debit", "152"]
	end

	def consumer
		@orders = SalesReceipt.where(:c_class => "Consumer Direct").order(sort_column + " " + sort_direction)
	end

	def index 
		@orders = Order.dash_orders.where.not(:c_class => classed_remove).order(sort_column + " " + sort_direction)
		@order_total = @orders.sum(:c_total)
		@invoices = Invoice.where(:c_date => @beg_month..@end_month)
		# @inv_temp = Invoice.where(:c_date => @prev_beg_month..@prev_end_month)
		@inv_dist = @invoices.where(:c_class => "Distributor Channel").where.not(:c_subtotal => 0)
		@log_update = Log.last

	# Channel calculations
		@orders_cw = Order.where(:c_date => @t_now.beginning_of_week..@t_now.end_of_week).where.not(:c_name => "Nate2 Davis").sum(:c_total)
		@invoice_total = Invoice.where(:c_date => @beg_month..@end_month).sum(:c_subtotal)
				
	# Current month top line sales calculations 
		@journal_debit = Journal.joins(:account_line_items).where(:txn_date => @beg_month..@end_month).where(@account_array).sum(@account_amount)
		@inv_gross_total = Invoice.joins(:items).where(:c_date => @beg_month..@end_month).where(@gs_account_id).sum(@homecurrency)
		@sr_gross_total = SalesReceipt.joins(:items).where(:txn_date => @beg_month..@end_month).where(@gs_account_id).sum(@homecurrency)
		@cm_gross_total = CreditMemo.joins(:items).where(:c_date => @beg_month..@end_month).where(@gs_account_id).sum(@homecurrency)
		@month_sales_receipts = SalesReceipt.where(:txn_date => @beg_month..@end_month).sum(:subtotal)
		@month_total = ((@inv_gross_total + @sr_gross_total) - (@cm_gross_total + @journal_debit))
		
	# Prior Month Top line sales calculations
		@pm_journal_debit = Journal.joins(:account_line_items).where(:txn_date => @prev_beg_month..@prev_end_month).where(@account_array).sum(@account_amount)
		@pm_inv_gross_total = Invoice.joins(:items).where(:c_date => @prev_beg_month..@prev_end_month).where(@gs_account_id).sum(@homecurrency)
		@pm_sr_gross_total = SalesReceipt.joins(:items).where(:txn_date => @prev_beg_month..@prev_end_month).where(@gs_account_id).sum(@homecurrency)
		@pm_cm_gross_total = CreditMemo.joins(:items).where(:c_date => @prev_beg_month..@prev_end_month).where(@gs_account_id).sum(@homecurrency)

	# Prior Month To DATE
		@journal_td_debit = Journal.joins(:account_line_items).where(:txn_date => @beg_month..@t_now).where(@account_array).sum(@account_amount)
		@inv_gross_td_total = Invoice.joins(:items).where(:c_date => @beg_month..@t_now).where(@gs_account_id).sum(@homecurrency)
		@sr_gross_td_total = SalesReceipt.joins(:items).where(:txn_date => @beg_month..@t_now).where(@gs_account_id).sum(@homecurrency)
		@cm_gross_td_total = CreditMemo.joins(:items).where(:c_date => @beg_month..@t_now).where(@gs_account_id).sum(@homecurrency)
		@month_sales_td_receipts = SalesReceipt.where(:txn_date => @beg_month..@t_now).sum(:subtotal)
		@month_td_total = ((@inv_gross_td_total + @sr_gross_td_total) - (@cm_gross_td_total + @journal_td_debit))

	#totaling subtotals
		@pmtd_journal_debit = Journal.joins(:account_line_items).where(:txn_date => @prev_beg_month..@prev_td_month).where(@account_array).sum(@account_amount)
		@pmtd_inv_gross_total = Invoice.joins(:items).where(:c_date => @prev_beg_month..@prev_td_month).where(@gs_account_id).sum(@homecurrency)
		@pmtd_sr_gross_total = SalesReceipt.joins(:items).where(:txn_date => @prev_beg_month..@prev_td_month).where(@gs_account_id).sum(@homecurrency)
		@pmtd_cm_gross_total = CreditMemo.joins(:items).where(:c_date => @prev_beg_month..@prev_td_month).where(@gs_account_id).sum(@homecurrency)
		@prior_mtd_total = ((@pmtd_inv_gross_total + @pmtd_sr_gross_total) - (@pmtd_cm_gross_total + @pmtd_journal_debit))
		@prior_m_total = ((@pm_inv_gross_total + @pm_sr_gross_total) - (@pm_cm_gross_total + @pm_journal_debit))
			@vs = ((@month_td_total - @prior_mtd_total) / @month_td_total) * 100
		@open_orders_count = Order.dash_orders.where.not(:c_class => classed_remove).count
		
		respond_to do |format|
		    format.html
		    # format.json  {@search = Customer.search(params[:term]) }
		    format.csv { send_data Order.to_csv(@orders), filename: "orders-#{Time.now.strftime("%d-%m-%Y %k%M")}.csv" }
		    # format.csv { send_data Invoice.inv_csv(@inv_temp), filename: "orders-#{Time.now.strftime("%d-%m-%Y %k%M")}.csv" }
  		end		
	end 

	def search
		render json: @search = Customer.search(params[:term])
	end

	def customer_details
      @cust = Customer.find(params[:id])
      respond_to do |format|
          format.js
      end

	    def _invoices
	  		render "_invoices", 
	        # locals: { elephant: some_thing },
	        layout: false
		end
    end

    private

    def sort_column
    	%w[c_ship c_date c_total c_name].include?(params[:sort]) ? params[:sort] : "c_date"
    end

    def sort_direction
    	%w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end

    def classed_remove
    	%w[Wholesale\ Direct nil wholesale].include?(params[:remove]) ? params[:remove] : "Wholesale Direct"
    end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
		
end

app/views/dashboard/_class_sales_chart.html.erb
<div id="class-sales-chart">
</div>


<script>
new Morris.Line({
  // ID of the element in which to draw the chart.
  element: 'class-sales-chart',
  // Chart data records -- each entry in this array corresponds to a point on
  // the chart.
  data: [
    { year: '2008', value: 20 },
    { year: '2009', value: 10 },
    { year: '2010', value: 5 },
    { year: '2011', value: 5 },
    { year: '2012', value: 20 }
  ],
  // The name of the data record attribute that contains x-values.
  xkey: 'year',
  // A list of names of data record attributes that contain y-values.
  ykeys: ['value'],
  // Labels for the ykeys -- will be displayed when you hover over the
  // chart.
  labels: ['Value']
});
</script>

app/views/dashboard/_invoices.html.erb
<thead>
    <tr>
        <th>Name</th>
        <th>Order #</th>
        <th>Date</th>
        <th>PO#</th>
        <th>Amount</th>
    </tr>
</thead>
<tbody>
<% @inv_dist.each do |f| %>
<tr>
	<td><%= link_to f.c_name, customer_path(f.customer_id) %></td>
	<td><%= link_to f.c_invoicenumber, invoice_path(f.id) %></td>
	<td><%= f.c_date.strftime("%m/%d/%Y") %></td>
	<td><%= f.c_po %></td>
	<td><%= number_to_currency(f.c_subtotal, :unit=> "$") %></td>
</tr>
<% end %>	
<tr> 
	<td colspan="5"><b>TOTAL<div class="pull-right"><%= number_to_currency(@inv_dist.sum(:c_subtotal), :unit => "$") %></div></b></td>
</tr>
</tbody>

app/views/dashboard/_month_sales_channel.html.erb
<%= content_tag :div, "", id: "orders_chart-2", data: {orders: Order.donut_chart} %>

<div id="month-sales-channel">
</div>


<script>
new Morris.Donut({
  // ID of the element in which to draw the chart.
  element: 'month-sales-channel',
  // Chart data records -- each entry in this array corresponds to a point on
  // the chart.
  data: $('#orders_chart-2').data('orders'),
  // The name of the data record attribute that contains x-values.
  xkey: 'c_date',
  // A list of names of data record attributes that contain y-values.
  ykeys: ['total_price'],
  // Labels for the ykeys -- will be displayed when you hover over the
  // chart.
  labels: ['Total Sales'],
  continuousLine: false,
  preUnits: '$',
  xLabels: "month",
  colors: [
    "#337ab7",
    "#f0ad4e",
    "#5cb85c",
    "#d9534f"
    ]
});
</script>

app/views/dashboard/_monthly_top_customers.html.erb
<%= content_tag :div, "", id: "bar-chart-1", data: {orders: Order.bar_chart} %>

<div id="top-customer-sales">
</div>


<script>
new Morris.Bar({
  // ID of the element in which to draw the chart.
  element: 'top-customer-sales',
  // Chart data records -- each entry in this array corresponds to a point on
  // the chart.
  data: $('#bar-chart-1').data('orders'),
  // The name of the data record attribute that contains x-values.
  xkey: 'name',
  // A list of names of data record attributes that contain y-values.
  ykeys: ['value'],
  // Labels for the ykeys -- will be displayed when you hover over the
  // chart.
  labels: ['Total Sales'],
  barColors: function (row, series, type) {
    if (type === 'bar') {
      return '#5cb85c';
    }
    else {
      return '#5cb85c';
    }
  }
});
</script>

app/views/dashboard/_sales_orders.html.erb
<thead>
    <tr>
        <th><%= sortable "c_name", "Name" %></th>
        <th>Order #</th>
        <th><%= sortable "c_date", "Order Date" %></th>
        <th><%= sortable "c_ship", "Ship Date" %></th>
        <th>PO#</th>
        <th><%= sortable "c_total", "Amount" %></th>
        <th>Status</th>
    </tr>
</thead>                                           
<tbody>                                            
<% @orders.each do |f| %>
<tr>
	<td><%= link_to f.c_name, customer_path(f.customer_id) %></td>
	<td><%= link_to f.invoice_number, order_path(f.id) %></td>
	<td><%= f.c_date.strftime("%m/%d/%Y") %></td>
	<td><%= f.c_ship.strftime("%m/%d/%Y") %></td>
	<td><%= f.c_po %></td>
	<td><%= number_to_currency(f.c_total, :unit=> "$") %></td>
	<td style="text-align:center;">
		<% if f.c_ack.nil? %>
			<% if f.c_class == "Distributor Channel" || f.c_class == "Amazon VC" %>
				<button type="button" class="btn btn-default btn-circle-2" data-container="body" data-toggle="popover" data-placement="left" data-content="" title="Pending Confirmation">
					<i class="fa fa-question"></i>
	            </button>
	          <% else %>
	          <button type="button" class="btn btn-disabled btn-circle-2">
					<i class="fa fa-minus"></i>
	            </button>
	           <% end %>
        <% elsif f.c_ack == "OK" %>
        	<button type="button" class="btn btn-success btn-circle-2" data-container="body">
				<i class="fa fa-check"></i>
			</button>
		<% else %>
			<button type="button" class="btn btn-warning btn-circle-2" data-container="body" data-toggle="popover" data-placement="left" data-content="<%= f.c_memo %>" title="<%= f.c_ack %>">
				<i class="fa fa-exclamation"></i> 
			</button>
		<% end %>
	</td>

</tr>
<% end %>	
<tr> 
	<td colspan="6"><b>TOTAL<div class="pull-right"><%= number_to_currency(@order_total, :unit => "$") %></div></b></td>
</tr>
</tbody>

app/views/dashboard/_weekly_sales_chart.html.erb
<%= content_tag :div, "", id: "orders_chart", data: {orders: Order.chart_data} %>

<div id="class-sales-chart">
</div>


<script>
new Morris.Line({
  // ID of the element in which to draw the chart.
  element: 'class-sales-chart',
  // Chart data records -- each entry in this array corresponds to a point on
  // the chart.
  data: $('#orders_chart').data('orders'),
  // The name of the data record attribute that contains x-values.
  xkey: 'c_date',
  // A list of names of data record attributes that contain y-values.
  ykeys: ['total_price'],
  // Labels for the ykeys -- will be displayed when you hover over the
  // chart.
  labels: ['Total Sales'],
  continuousLine: false,
  preUnits: '$',
  xLabels: "week"
});
</script>

app/views/dashboard/_weekly_tpr_chart.html.erb
<%= content_tag :div, "", id: "credit_memos", data: {credit: CreditMemo.chart_data('week')} %>

<div id="credit-tpr-chart">
</div>


<script>
new Morris.Line({
  // ID of the element in which to draw the chart.
  element: 'credit-tpr-chart',
  // Chart data records -- each entry in this array corresponds to a point on
  // the chart.
  data: $('#credit_memos').data('credit'),
  // The name of the data record attribute that contains x-values.
  xkey: 'cr_date',
  // A list of names of data record attributes that contain y-values.
  ykeys: ['total_tpr'],
  // Labels for the ykeys -- will be displayed when you hover over the
  // chart.
  labels: ['Total Deductions'],
  continuousLine: false,
  preUnits: '$',
  xLabels: "week",
  lineColors: ['#d9534f']
});
</script>

app/views/dashboard/consumer.html.erb



        <div id="page-wrapper" style="min-height: 629px;">
            <div class="row">
                <div class="col-lg-9 col-md-8">
                    <h1 class="page-header">Dashboard</h1>                  
                </div>
                <!-- /.col-lg-12 -->
                <div class="col-lg-3 col-md-4" style="text-align:right;"">
                    <span class="page-header" style="border-bottom:unset;line-height:4em;font-size:12px;">
                        <i class="btn <% if @log_update.nil? or @log_update.updated_at < (Time.now - 1.day) %>btn-danger<% else %>btn-success<% end %> btn-circle" style="width:20px;height:20px;padding:2px 0;font-size: 10px;"><i class="fa fa-check"></i>
                        </i>
                        Last Updated: <%if @log_update.nil? %>n/a<%else%><%=@log_update.updated_at.strftime("%m-%d-%y %l:%M")%> <%end%>
                    </span>
                </div>
                
            </div>

            <!-- Nate's Row -->
               <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-dollar"></i> Sales Figures
                    </div>
                </div>


            <!-- /.row -->
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-2">
                                    <i class="fa fa-tasks fa-2x"></i>
                                </div>
                                <div class="col-xs-10 text-right">
                                    <div class="huge">
                                    	$<%= number_to_human(@month_total, :format => '%n%u', :units => { :thousand => 'K' }) %>
                                    </div>
                                    <div><%=Time.now.strftime("%B")%> Sales to Date</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-2">
                                    <i class="fa fa-tasks fa-2x"></i>
                                </div>
                                <div class="col-xs-10 text-right">
                                    <div class="huge">
                                    <%= number_to_percentage(@vs, precision: 2) %>
                                    </div>
                                    <div>vs Prior Month to Date</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-2">
                                    <i class="fa fa-shopping-cart fa-2x"></i>
                                </div>
                                <div class="col-xs-10 text-right">
                                    <div class="huge">
                                    $<%= number_to_human(@prior_m_total, :format => '%n%u', :units => { :thousand => 'K' }) %>
                                    
                                    </div>
                                    <div><% month_ago = Time.now - 1.month %><%= month_ago.strftime("%B") %> Sales</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-2">
                                    <i class="fa fa-support fa-2x"></i>
                                </div>
                                <div class="col-xs-10 text-right">
                                    <div class="huge">
                                        <%= @open_orders_count %>
                                    </div>
                                    <div>Open Orders!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-8 col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                        <i class="fa fa-bar-chart-o fa-fw"></i>
                        Sales by Week
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div>
                                <%= render :partial => 'weekly_sales_chart' %>
                                </div>
                            </div>
                        </div>
              
                    </div>
                </div>

                <div class="col-lg-4 col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                        <i class="fa fa-bar-chart-o fa-fw"></i>
                        <%=Time.now.strftime("%B")%> Sales by Class <sub>*if filled in full</sub>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div>
                                <%= render :partial => 'month_sales_channel' %>
                                </div>
                            </div>
                        </div>
              
                    </div>
                </div>
            </div>

             <div class="row">
                <div class="col-lg-6 col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                        <i class="fa fa-bar-chart-o fa-fw"></i>
                        Deductions by Week
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div>
                                <%= render :partial => 'weekly_tpr_chart' %>
                                </div>
                            </div>
                        </div>
              
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                        <i class="fa fa-bar-chart-o fa-fw"></i>
                        Top Customers for <%=Time.now.strftime("%B")%>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div>
                                <%= render :partial => 'monthly_top_customers' %>
                                </div>
                            </div>
                        </div>
              
                    </div>
                </div>

            </div>

            
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-bar-chart-o fa-fw"></i> Order Table
                            <div class="pull-right">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                        <span id="type-of-orders">Sales Orders</span>
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu pull-right" id="sorting" role="menu">
                                        <li><a class="append-sales-orders" href="#">Sales Orders</a>
                                        </li>
                                        <li><a class="append-invoices" href="#">Invoices</a>
                                        </li>
                                        <li class="divider"></li>
                                        <li><%= remove_class "nil", "Add Wholesale" %></span>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                       
                                  
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="table-responsive">
                                        <table class="table table-bordered table-hover table-striped" id="order-table">
                                                <%= render :partial => 'invoices' %>
                                        </table>
                                        <table class="table table-bordered table-hover table-striped" id="order-sales-table">
                                            <%= render :partial => 'sales_orders' %>
                                        </table>
                                    </div>
                                    <!-- /.table-responsive -->
                                </div>                               
                    		</div>
                	    </div>
                    </div>
                </div>
            </div>

             
        <!-- /#page-wrapper -->

    <script>
    	$(function() {
        
      $('[data-toggle="popover"]').popover({
        trigger: 'focus'
    })
      
      $("#order-table").hide();
      
    
      $('.append-invoices').on('click', function(e) {
        e.preventDefault();
        $("#order-sales-table").hide();       
        $("#order-table").show();
        $("#type-of-orders").text("Invoices");    
    });
    $('.append-sales-orders').on('click', function(e) {
        e.preventDefault();
        $("#order-sales-table").show();       
        $("#order-table").hide();
        $("#type-of-orders").text("Sales Orders");
    });
});
	</script>    