config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations'}, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  get '/health-check/' => 'auth#sign_in'
  resources :users

  mount ReportsKit::Engine, at: '/'

  resources :customers
  get 'qbwc/action' => 'qbwc#_generate_wsdl'
  get 'qbwc/qwc' => 'qbwc#qwc'
  wash_out :qbwc

  constraints defaults: { format: :json } do
    match '/:webhook_token' => 'welcome#api', as: :subscription_webhook, via: [:options, :post]
  end
  

  root :to => 'users#homepages'

  get 'qbwc_settings' => 'users#qbwc_settings'
  put 'qbwc_enabled' => 'users#qbwc_enabled'
  put 'qb_helper' => 'users#qb_helper'

  get :search, controller: :dashboard
    
  resources :orders do resources :comments end

  resources :orders
  resources :items
  resources :sites
  resources :site_inventories
  resources :bills
  resources :trackings
  resources :invoices
  resources :accounts
  resources :credit_memos
  resources :reports
  resources :fulfillment
  
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  get '/email_send' => 'trackings#email_send'
    
  get '/customer_details' => 'orders#customer_details'

  get '/dashboard' => 'dashboard#index'
  get '/dashboard/consumer' => 'dashboard#consumer'
  
    

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	has_many :line_items, :dependent => :destroy, foreign_key: "invoice_id"
    has_many :items, through: :line_items, foreign_key: "invoice_id"
    has_many :sites, through: :line_items, foreign_key: "site_id"
    belongs_to :customer


scope :fulfill_invoice, -> {Invoice.where(tracking: nil).where(:c_class => "Wholesale Direct").where("c_date > ?", Time.now.beginning_of_year)}

    default_scope {where(:deleted => nil)}




include ReportsKit::Model
  reports_kit do
    aggregation :sum_of_invoices, [:sum, 'line_items.homecurrency_amount']
    contextual_filter :for_customer, ->(relation, context_params) { relation.where(customer_id: context_params[:customer_id])}
    contextual_filter :for_item, ->(relation, context_params) { relation.joins(:line_items).where(item_id: context_params[:item_id])}
    # contextual_filter :for_item, ->(relation, context_params) { relation.where(item_id: context_params[:item_id]) }
    dimension :monthly_group, joins: :items, group: "to_char(date_trunc('month', invoices.c_date), 'MM-YY Mon')", order_by: "to_char_date_trunc_month_invoices_c_date_yy_mon DESC"
    # contextual_filter :for_invoice_items, ->(relation, context_params) {relation.where("items.account_id = 152")}
    # dimension :customer_group, group: '(customers.name)'
    filter :is_accounted, :boolean, conditions: ->(relation) { relation.where("items.account_id = 152") }
    # filter :is_an_item, :boolean, conditions: ->(relation) { relation.where("items.name LIKE ?", "%FG:12/12ct Master%") }
    # filter :for_item, :boolean, conditions: ->(relation) { relation.where("items.account_id = 152") }
    # dimension :date_month, where: "date_trunc(month, invoices.c_date)"
  end

  # STATUSES = %w(draft private published).freeze

  def to_s
     c_name
  end



  def self.inv_csv(order)
        attributes = %w{c_invoicenumber id c_name c_po c_date c_scac c_bol c_ship c_via c_ship1 c_ship2 c_ship3 c_ship4 c_ship5 c_shipcity c_shipstate invoice_number customer_id tracking fob c_subtotal}
        li_attributes = %w{invoice_id qty description homecurrency_amount}
        multi_header = %w{invoice_id qty description homecurrency_amount name code upc account_id c_invoicenumber id c_name c_po c_date c_scac c_bol c_ship c_via c_ship1 c_ship2 c_ship3 c_ship4 c_ship5 c_shipcity c_shipstate customer_id c_subtotal}
        CSV.generate(headers: true) do |csv|
        csv << multi_header
            order.each do |orders|
                orders.line_items.each do |items|
                    orderinfo = orders.attributes.values_at(*attributes)
                    # row1 = orderinfo.join(", ")
                    row = items.attributes.values_at(*li_attributes)
                    row += [items.item.name, items.item.code, items.item.upc, items.item.account_id]
                    row += orderinfo
                    csv << row
                end
            end
        end
    end

    def self.inv_chart_data(starting, ending, interval)
        total_invoices = amounts_by_interval(starting.to_date, ending.to_date, interval)
        total_invoices_py = amounts_by_interval(starting.to_date.prev_year, ending.to_date.prev_year, interval)
        total_srs = SalesReceipt.amounts_by_interval(starting.to_date, ending.to_date, interval)
        total_srs_py = amounts_by_interval(starting.to_date.prev_year, ending.to_date.prev_year, interval)
        total_credits = CreditMemo.amounts_by_interval(starting.to_date, ending.to_date, interval)
        total_credits_py = amounts_by_interval(starting.to_date.prev_year, ending.to_date.prev_year, interval)
        total_journals = Journal.amounts_by_interval(starting.to_date, ending.to_date, interval)
        total_journals_py = amounts_by_interval(starting.to_date.prev_year, ending.to_date.prev_year, interval)
        # total_cy = total_invoices.map do |date, amount|
        #     amount += total_srs.map do |date2, amount2|
        #         if date.between?(date2-1.day, date2+1.day) ? amount2 : 0
        #             amount = amount + amount2
        #         end.sum
        #     end
        #     amount += total_credits.each do |date2, amount2|
        #         if date.between?(date2-1.day, date2+1.day) ? amount2 : 0
        #             amount = amount - amount2
        #         end.sum
        #     end
        #     amount+= total_journals.each do |date2, amount2|
        #         if date.between?(date2-1.day, date2+1.day) ? amount2 : 0
        #             amount = amount + amount2
        #         end.sum
        #     end
        # end    
        # total_py = total_invoices_py.map do |date, amount|
        #     total_srs_py.each do |date2, amount2|
        #         if date.between?(date2-1.day, date2+1.day)
        #             amount = amount + amount2
        #         end
        #     end
        #     total_credits_py.each do |date2, amount2|
        #         if date.between?(date2-1.day, date2+1.day)
        #             amount = amount - amount2
        #         end
        #     end
        #     total_journals_py.each do |date2, amount2|
        #         if date.between?(date2-1.day, date2+1.day)
        #             amount = amount + amount2
        #         end
        #     end
        # end     
        total_invoices.map do |c, d|
            ly = 0
            total_invoices_py.each do |e, f|
           
                if c.strftime("%m") == e.strftime("%m")
                    ly = f
                end
            end
            {date: c+1.day, total: d, total_ly: ly}
        end



        # total_prices.map do |a, b|
        #     {
        #         date: a,
        #         total: b || 0
        #     }
        # end
    end

    # this interval chart cannot supports multiple customer grouping. 
    def self.amounts_by_interval(starting, ending, interval)
        orders = joins(:items).where(c_date: starting.beginning_of_day..ending.beginning_of_day)
        orders = orders.where("items.account_id = 152")
        orders = orders.group("date_trunc('#{interval}', c_date)")
        orders = orders.order("c_date asc")
        orders = orders.select("date_trunc('#{interval}', c_date) as c_date, sum(line_items.homecurrency_amount) as subtotal")
        orders.each_with_object({}) do |order, prices|            
            prices[order.c_date.to_date] = order.subtotal.round(2)           
        end
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
	before_action :authenticate_user!
	before_action :admin_only, except:[:show, :index, :update]

	def index
		@invoices = Invoice.all.order "id ASC"
    	@inv1 = Invoice.where("c_date >= ?", 2.months.ago).paginate(:page => params[:page], :per_page => 50).order('c_date ASC')
      @invoice_limit = Invoice.where("c_date >= ?", 3.months.ago)

    respond_to do |format|
      format.html
      format.csv { send_data Invoice.inv_csv(@invoice_limit), filename: "invoices-#{Time.now.strftime("%d-%m-%Y %k%M")}.csv" }
    end    
	end

	def show
      @order = Invoice.find(params[:id])
  	end
  	def update
	  	respond_to do |format|
        format.html {
          @track = Invoice.find(params[:id])
          @track.update(track_params)
          redirect_to trackings_path}
        format.js
        format.json {
          @track = Invoice.find(params[:id])
          @track.update(email_params)
          render json: @track}
      end
    end

  	def email_params
      params.permit(:to_email, :emailed)
 	end
 	 def track_params
      params.require(:tracking).permit(:memo, :tracking, :ship_method, :email, :emailed, :packages, :ship1, :ship2, :ship3, :shipcity, :shipstate, :shippostal, :shipcountry, :name, :to_email)
  end

end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_invoice_display.html.erb
<% @order.line_items.each do |o| %>
    <tr>
        <td><%= link_to o.item_id, item_path(o.item_id) %></td>
        <td><%= o.item.name %></td>
        <td><%= o.description %></td>
        <td><%= o.qty %></td>
            <% if( ! o.site.nil? ) %>                   
                <td><%= o.site.name %></td>
            <%  else %>
                <td></td>
            <% end %>
                
        <td><%= number_to_currency(o.amount) %></td>
    </tr>
<% end %>
<tr><td style="padding-right:2%;" align="right" colspan="6"><b>Total: <%= number_to_currency(@order.c_subtotal) %></b></td></tr>

app/views/invoices/index.html.erb
 <div id="page-wrapper" style="min-height: 629px;">
    
    <div class="row">
        <div class="col-lg-12">
			<h1 class="page-header">Invoices</h1>

			<%=  will_paginate @inv1, renderer: BootstrapPagination::Rails %>			

			<div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover table-striped">
                                <thead>
                                    <tr>
                                    	<th>#</th>
                                        <th>Name</th>
                                        <th>Order #</th>
                                        <th>Date</th>
                                        <th>PO#</th>
                                        <th>Amount</th>
                                    </tr>
                                </thead>
                               
                                <tbody class="order-table">
                               	<% @inv1.each_with_index do |c, index| %>
                                	<tr>
                                    	<td><%= index + 1 %>.</td>
										<td><%= c.customer.name %></td>
		 								<td><%= link_to c.c_invoicenumber, invoice_path(c.id) %></td>
										<td><%= c.c_date.strftime("%m/%d/%Y") %></td>
										<td><%= c.c_po %></td>
										<td><%= number_to_currency(c.c_subtotal, :unit=> "$") %></td>
									</tr>
								<% end %>
                               	</tbody>
                            </table>
                        </div>
                        <!-- /.table-responsive -->
                    </div>                               
        		</div>
    	    </div>
            <!-- end of the row -->

		</div>
	</div>
</div>

app/views/invoices/show.html.erb
 <div id="page-wrapper" style="min-height: 629px;">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><%= link_to @order.customer.name, customer_path(@order.customer.id) %></h1>                  
                </div>
                <!-- /.col-lg-12 -->
            </div>


            <!-- /.row -->
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">                            
                                <div class="col-xs-12 text-right">
                                    <div class="invoice-large">
                                        <%= @order.c_invoicenumber %>
                                    </div>
                                    <div>Invoice Number</div>
                                </div>
                            </div>
                        </div>                    
                    </div>
                </div>

                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-12 text-right">
                                    <div class="invoice-large">
                                   <%= @order.c_date.strftime("%m/%d/%Y") if @order.c_date %>
                                    </div>
                                    <div>Order Date</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-12 text-right">
                                    <div class="invoice-large">
                                        <%= number_to_currency(@order.c_subtotal, :unit => "$",precision: 2) %>
                                    </div>
                                    <div>Invoice Total</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

    <div class="row">
    <div class="col-lg-6 col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
            <i class="fa fa-clock-o fa-fw"></i>
                Shipping Information
            </div>
                    <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="list-group">
                    <a href="#" class="list-group-item">
                        <span class="text-muted small">
                            <%= @order.c_ship1 %><br /></span>
                            <%= @order.c_ship2 %><br />
                            <%= raw(@order.c_ship3 + '<br />') if !@order.c_ship3.blank? %>
                            <%= raw(@order.c_ship4 + '<br />') if !@order.c_ship4.blank? %>
                            <%= raw(@order.c_ship5 + '<br />') if !@order.c_ship5.blank? %>
                            <%= @order.c_shipcity %>, <%= @order.c_shipstate %> <%= @order.c_shippostal %>
                       </span>
                    </a>
                    <a href="#" class="btn btn-default btn-block color-grey" >
                        Ship Date: <%= @order.c_ship.strftime("%m/%d/%Y") if @order.c_ship %>    
                    </a>
                    
                </div>
            </div>
          <!-- /.panel-body -->
        </div>
    </div>
    </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-bar-chart-o fa-fw"></i> Order Table
                    </div>

                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="table-responsive">
                                    <table class="table table-bordered table-hover table-striped">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>Product #</th>
                                                <th>Description</th>
                                                <th>Qty</th>
                                                <th>Site</th>
                                                <th>Amount</th>
                                            </tr>
                                        </thead>
                                        <tbody class="order-sales-table">
                                                <%= render :partial => 'invoice_display' %>
                                        </tbody>  
                                    </table>
                                <!-- /.table-responsive -->
                                </div>                               
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
$(function() { 
    $('#invoice-button').click(function(event){
        $.ajax({
            url: '../invoice/',
            type: 'POST',
            dataType: 'json',
            contentType: 'application/json',
            data: JSON.stringify({ id: '2782'})
        });
    });
});

</script>