config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations'}, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  get '/health-check/' => 'auth#sign_in'
  resources :users

  mount ReportsKit::Engine, at: '/'

  resources :customers
  get 'qbwc/action' => 'qbwc#_generate_wsdl'
  get 'qbwc/qwc' => 'qbwc#qwc'
  wash_out :qbwc

  constraints defaults: { format: :json } do
    match '/:webhook_token' => 'welcome#api', as: :subscription_webhook, via: [:options, :post]
  end
  

  root :to => 'users#homepages'

  get 'qbwc_settings' => 'users#qbwc_settings'
  put 'qbwc_enabled' => 'users#qbwc_enabled'
  put 'qb_helper' => 'users#qb_helper'

  get :search, controller: :dashboard
    
  resources :orders do resources :comments end

  resources :orders
  resources :items
  resources :sites
  resources :site_inventories
  resources :bills
  resources :trackings
  resources :invoices
  resources :accounts
  resources :credit_memos
  resources :reports
  resources :fulfillment
  
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  get '/email_send' => 'trackings#email_send'
    
  get '/customer_details' => 'orders#customer_details'

  get '/dashboard' => 'dashboard#index'
  get '/dashboard/consumer' => 'dashboard#consumer'
  
    

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable, :timeoutable
         
    has_many :recipients, class_name: "Notification", foreign_key: "recipient_id"
    has_many :actors, class_name: "Notification", foreign_key: "actor_id"
    has_many :notifications 
#     attr_accessor :password
# #    attr_accessible :name, :email, :password, :password_confirmation

#     email_regex = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

#     validates   :name,      :presence   => true,
#                 :length                 => { :maximum => 50 }
#     validates   :email,     :presence   => true,
#                 :format                 => { :with => email_regex },
#                 :uniqueness             => { :case_sensitive => false }

#     validates   :password,  :presence   => true, on: :create,
#                 :confirmation           => true,
#                 :length                 => { :within => 6..40 }

#     before_save :encrypt_password

#     def has_password?(submitted_password)
#         encrypted_password == encrypt(submitted_password)
#     end

#     #method of class, was the email and password valid?
#     def self.authenticate(email, submitted_password)
#         user = find_by_email(email)

#         return nil if user.nil?
#         return user if user.has_password?(submitted_password)
#     end
    
#     private
#         def encrypt_password
#             #salting time....maybe some pepper?
#             self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{password}") if self.new_record?
            
#             #encrypt me some yummy password and store that info
#             self.encrypted_password = encrypt(password)
#         end
    
#         #encrypt password with salt and enjoy.
#         def encrypt(pass)
#             Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
#         end
    
    has_attached_file :avatar, :styles => { :medium=> "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
    
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  prepend_before_filter :admin_only, except:[:edit, :update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end


  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:phone, :avatar, :role, :name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:phone, :avatar, :role, :name])
  end

  def active_for_authentication?
    #remember to call the super
    #then put our own check to determine "active" state using 
    #our own "is_active" column
    # super and current_user.role == 'admin'
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :admin_only, except:[:edit, :update, :show]
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]
    # you can use this to make exceptions ", except:[:new, :create, :edit, :update]"
  
  def index
      if current_user.role = "admin"
      @user = User.all.order('created_at asc') 
    else
      redirect_to_user_path(current_user)
    end
  end
  
  def new
      # super
      @user = User.new
  end
    
  def create
        # super
        @user = User.new(user_params)
        if @user.save
          redirect_to users_path, notice: "User was successfully created."
          # sign_in @user
        else
          #render :text => "here"
          render action: "new"
        end
  end

  def show
      @user = User.find(params[:id])
      @notify_o = current_user.recipients.where(:notifiable_type => "Order").order(:created_at => "DESC").limit(10)
      @notify_cm = current_user.recipients.where(:notifiable_type => "CreditMemo").order(:created_at => "DESC").limit(10)
      @notify_c = current_user.recipients.where(:notifiable_type => "Customer").order(:created_at => "DESC").limit(10)
  end
      
  def edit
      @user = User.find(params[:id]) 
      end
      
  def update
      @user = User.find(params[:id])
      @user.update(user_params)
      p @user
  end

  def homepages
     if current_user.homepage == nil
      redirect_to dashboard_path
     elsif current_user.homepage == "fulfillment"
      redirect_to fulfillment_index_path
     else
      redirect_to dashboard_consumer_path
     end
  end

  def qbwc_settings
    if current_user.role = "admin" && current_user.email = "nate@zingbars.com"
      @qbwc = QBWC.jobs
      @initial = QbHelper.first
      @logs = Log.all.order(:created_at => "DESC").limit(5)
    else
      redirect_to users_path, notice: "You do not have access to this page."
    end
  end

  def qbwc_enabled
    worker_name = params[:id]
    enabling = params[:qbwc_enabled]
    QBWC.get_job(worker_name).enabled = enabling
    a = QBWC.get_job(worker_name).enabled?
    respond_to do |format|
      format.js
      format.json {        
        render json: {qbwc_enabled: a, id: worker_name} }
    end
  end

  def qb_helper
    @initial = QbHelper.first
    start_date = params[:start]
    end_date = params[:end]
    initial_tf = params[:initial_load]
    @initial.start = start_date
    @initial.end = end_date
    @initial.initial_load = initial_tf    
    @initial.save
     respond_to do |format|
        format.js
        format.json {
          render json: {initial_load: initial_tf, start: start_date, end: end_date}
        }
      end
  end
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:phone, :avatar, :role])
  # end

  # # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:phone, :avatar, :role])
  # end


  # def destroy
  #       # sign_out
  #       # redirect_to signin_path
  #   end
        
  private
  
  def qbwc_params
      params.permit(:qbwc_enabled, :id)
  end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :role, :phone, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_notification_creditmemo_view.html.erb
<% @notify_cm.each do |f| %>
<tr>
		<td><%= f.notifiable.id %></td>
		<td><%= link_to f.notifiable.c_name, customer_path(f.notifiable.customer_id) %></td>
		<td><%= link_to f.notifiable.c_invoicenumber, order_path(f.notifiable.id) %></td>
		<td><%= number_to_currency(f.notifiable.c_subtotal, :unit=> "$") %></td>
		<td><%= f.created_at.strftime("%m/%d/%Y") %></td>
</tr>
<% end %>

app/views/users/_notification_customer_view.html.erb
<% @notify_c.each do |f| %>
<tr>
		<td><%= f.notifiable.id %></td>
		<td><%= link_to f.notifiable.name, customer_path(f.notifiable.id) %></td>
		<td><%= f.notifiable.customer_type %></td>
		<td><%= f.notifiable.email %></td>
		<td><%= f.created_at.strftime("%m/%d/%Y") %></td>
</tr>
<% end %>

app/views/users/_notification_order_view.html.erb
<% @notify_o.each do |f| %>
<tr>
		<td><%= f.notifiable.id %></td>
		<td><%= link_to f.notifiable.c_name, customer_path(f.notifiable.customer_id) %></td>
		<td><%= link_to f.notifiable.c_po, order_path(f.notifiable.id) %></td>
		<td><%= number_to_currency(f.notifiable.c_total, :unit=> "$") %></td>
		<td><%= f.created_at.strftime("%m/%d/%Y") %></td>
</tr>
<% end %>

app/views/users/edit.html.erb
<h1><%= @user.id %></h1>
<% if @current_user.role == "admin" %>
<%= simple_form_for @user, url: user_path do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br />
   
    <%= f.label :role %>
    <%= f.text_field :role %>
    <br />
    <%= f.input :password %>
    <%= f.input :password_confirmation %>

    <%= f.input :avatar, as: :file %>
        
<%= f.submit "Save Changes" %>
<% end %>
<% else %> 
<h4>You are not an admin and do not have access to this page.</h4>
<% end %>

app/views/users/index.html.erb
 <div id="page-wrapper" style="min-height: 629px;">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Current Users</h1>                  
			<% i=1 %>
			<% @user.each do |user| %>
			    <%= i %> .  
			    <% i=i+1 %>
			    <%= link_to user.name, user %> - <%= user.role %><br />
			<% end %>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<div id="page-wrapper" style="min-height: 629px;">  
	<div class="row">
	    <div class="col-md-4 col-md-offset-4">
	        <div class="login-panel panel panel-default">
	            <div class="panel-heading">
	                <h3 class="panel-title">Register New Account</h3>
	            </div>


				<div class="panel-body">
	                <%= simple_form_for(@user, url: users_path(@user)) do |f| %>
	                    <form role="form" _lpchecked="1" lpformnum="1">
	                        <fieldset>

	                        	<%= f.input :name, required: true %>
	                            <div class="form-group">
	                                <%= f.label :avatar %>
	                                <%= f.file_field :avatar %>
	                            </div>
	                            <div class="form-group">
	                                <%= f.input :role, as: :string %>


	                            </div>
	                            <div class="form-group">
	                                 <%= f.input :email, required: true, autofocus: true %>
	                                <%= f.input :phone, as: :tel %>
	                            </div>
	                            <div class="form-group">
    <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
    <%= f.input :password_confirmation, required: true %>
	                            </div>
	                            <%= f.button :submit, class: "btn btn-lg btn-success btn-block"%>
	                        </fieldset>
	                    </form>
	                <% end %>
	                <% if flash[:error] %>
				    	<p><%= flash[:error] %></p>
					<% end %>
					<% if flash[:notice] %>
					    <p><%= flash[:notice] %></p>
					<% end %>
	            </div>
	        </div>
		</div>
	</div>
</div>

app/views/users/qbwc_settings.html.erb
 <div id="page-wrapper" style="min-height: 629px;">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">QBWC - List Of Queries</h1>                  
			<% i=1 %>
			<% b = @qbwc.to_a %>
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
           <div class="alert alert-info fade in qb-alert">
                QBWC settings were successfully updated!
            </div>
            <div class="col-lg-4">
                  <%= simple_form_for @initial, :url => '/qb_helper/', remote: true do |f| %>
                    <%= f.input :initial_load, as: :boolean, label: "Initial Load:" %>
                    <%= f.input :start, as: :date, label: "Start Date" %>
                    <%= f.input :end, as: :date, label: "End Date" %>
                    <%= f.submit class: 'checkbox-qb-initial' %>
                <% end %>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-12">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                            <tr>
                            	<th>#</th>
                                <th>Worker Name</th>
                                <th>Worker Class</th>
                                <th>Date Range</th>
                                <th>Status</th>
                                <th>Enabled?</th>
                            </tr>
                        </thead>
						<tbody class="order-table">
                       	<% b.each_with_index do |qbwc, index| %>
                        <% worker_class = qbwc.worker_class.to_s %>
                        <% log_dates = Log.where(worker_name: qbwc.worker_class).where(status: "Completed").order(created_at: :desc).limit(1) %>
                        <% log_status = Log.where(worker_name: qbwc.worker_class).where(status: "Updates").order(created_at: :desc).limit(1) %>
                        	<tr>
                                <td><%= index + 1 %>.</td>
								<td><%= qbwc.name %></td>
                                <td><%= qbwc.worker_class %></td>
								<td>
                                    <% if !log_dates[0].nil? %>
                                    <%= log_dates[0].start_date.strftime("%m/%d/%Y") %> to <%= log_dates[0].end_date.strftime("%m/%d/%Y") %>
                                    <% end %>                                            
                                </td>
                                <td>
                                    <% if !log_status[0].nil? %>
                                        <%= log_status[0].log_msg %> on <%= log_status[0].updated_at.strftime("%m/%d/%Y") %>
                                    <% end %>
                                </td>
                                <td>
									<%= form_tag '/users/qbwc_enabled', remote: true do %> 
						       			<%= check_box_tag qbwc.name, 'yes', qbwc.enabled?, class: 'checkbox-qbwc' %>
	       							<% end %>
	       						</td>
							</tr>
						<% end %>
                       	</tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>                               
		</div>
    </div>
    <div class="panel-body">
         <div class="row">
            <div class="col-lg-12">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Log Name</th>
                                <th>Created At</th>
                                <th>Status</th>
                                <th>Log Message</th>
                            </tr>
                        </thead>
                        <tbody class="order-table">
                        <% @logs.each_with_index do |log, index| %>
                            <tr>
                                <td><%= index + 1 %>.</td>
                                <td><%= log.worker_name %></td>
                                <td><%= log.created_at %></td>
                                <td><%= log.status %></td>
                                <td><%= log.log_msg %></td>
                            </tr>
                        <% end %>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>                               
        </div>
    </div>    
</div>

app/views/users/show.html.erb
<div id="page-wrapper" style="min-height: 629px;">
        <div class="row">
        <div class="col-lg-12 col-xs-12">
        <h1 class="page-header">User Profile</h1>
        </div>
        </div>

        <div class="row">
        <div class="col-lg-6">
                      <div class="panel panel-default">
                      
                       <div class="panel-body">
                      <div class="col-lg-3">
                        <div class="round-image-150"><%= image_tag(current_user.avatar.url(:medium)) %></div>
                     <p style="text-align:center;padding-top: 5%;"><%= link_to raw('<i class="fa fa-user fa-fw"></i>Edit Info'), edit_user_registration_path %></p>
                 
                      </div>
                      <div class="col-lg-9" >
                          <div class="container" >
                            <h2><%= @user.name %></h2>
                            <p><b><%= @user.role %></b></p>
                          <div>
                            <p><span class="fa fa-phone fa-fw" style="width:50px;"></span><%= @user.phone %></p>
                            <p><span class="fa fa-envelope fa-fw" style="width:50px;"></span><%= @user.email %></p>
                          <div class="col-sm-5 col-xs-6 tital " >Join Date: <%= @user.created_at.strftime("%m-%d-%Y") %>
                          </div>
                      </div>
                </div>
            </div>
            </div>
          </div>
        </div>
      </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
          <div class="panel-heading" style="font-size:2em;">
            <i class="fa fa-bell fa-fw" style="color:#337ab7;"></i> Recent Notifications
            <div class="pull-right">
            </div>
          </div>
            
            <div class="panel-body">

          
              <div class="panel panel-default">
            <div class="panel-heading">
              <i class="fa fa-dollar fa-fw"></i> Recent Order Notifications
            </div>
            <div class="table-responsive">
              <table class="table table-bordered table-hover table-striped">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>PO#</th>
                    <th>Amount</th>
                    <th>Date Created</th>
                  </tr>
                </thead>
                <tbody class="order-sales-table">
                 <%= render :partial => 'notification_order_view' %>
                </tbody>  
              </table>
            </div>
          </div>
       
       <div class="panel panel-default">
            <div class="panel-heading">
              <i class="fa fa-dollar fa-fw" style="color:#F00;"></i> Recent Credit Memo Notifications
              <div class="pull-right">
              </div>
            </div>
            <div class="table-responsive">
              <table class="table table-bordered table-hover table-striped">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Invoice #</th>
                    <th>Amount</th>
                    <th>Date Created</th>
                  </tr>
                </thead>
                <tbody class="order-sales-table">
                 <%= render :partial => 'notification_creditmemo_view' %>
                </tbody>  
              </table>
            </div>
          </div>

           <div class="panel panel-default">
            <div class="panel-heading">
              <i class="fa fa-users fa-fw"></i> Recent New Customer Notifications
              <div class="pull-right">
              </div>
            </div>
            <div class="table-responsive">
              <table class="table table-bordered table-hover table-striped">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Email</th>
                    <th>Date Created</th>
                  </tr>
                </thead>
                <tbody class="order-sales-table">
                 <%= render :partial => 'notification_customer_view' %>
                </tbody>  
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%= link_to raw('<i class="fa fa-sign-out fa-fw"></i>Logout'), destroy_user_session_path, :method => :delete %>
</div>

			<br />
    	<br />

app/views/users/update.html.erb
<h2>updated at <%= Time.now %></h2>
<h1><%= link_to @user.name, edit_user_path %></h1>
<br />
<%= @user.role %>