config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations'}, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  get '/health-check/' => 'auth#sign_in'
  resources :users

  mount ReportsKit::Engine, at: '/'

  resources :customers
  get 'qbwc/action' => 'qbwc#_generate_wsdl'
  get 'qbwc/qwc' => 'qbwc#qwc'
  wash_out :qbwc

  constraints defaults: { format: :json } do
    match '/:webhook_token' => 'welcome#api', as: :subscription_webhook, via: [:options, :post]
  end
  

  root :to => 'users#homepages'

  get 'qbwc_settings' => 'users#qbwc_settings'
  put 'qbwc_enabled' => 'users#qbwc_enabled'
  put 'qb_helper' => 'users#qb_helper'

  get :search, controller: :dashboard
    
  resources :orders do resources :comments end

  resources :orders
  resources :items
  resources :sites
  resources :site_inventories
  resources :bills
  resources :trackings
  resources :invoices
  resources :accounts
  resources :credit_memos
  resources :reports
  resources :fulfillment
  
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  get '/email_send' => 'trackings#email_send'
    
  get '/customer_details' => 'orders#customer_details'

  get '/dashboard' => 'dashboard#index'
  get '/dashboard/consumer' => 'dashboard#consumer'
  
    

end

app/models/item.rb
class Item < ActiveRecord::Base
    # has_many :site_inventories
    has_many :sites
    belongs_to :order
    has_many :invoices
    has_many :sales_receipts
	has_many :credit_memos    
    has_many :line_items
    belongs_to :account, foreign_key: "account_id"

    default_scope {where(:deleted => nil)}


    include ReportsKit::Model
    reports_kit do
        # contextual_filter :for_item, ->(relation, context_params) { relation.where(id: context_params[:item_id])}
        # contextual_filter :for_customer, ->(relation, context_params) { relation.where(customer_id: context_params[:id]) }
    end

    def self.inv_chart_data(starting, ending, interval)
        total_prices = amounts_by_interval(starting.to_date, ending.to_date, interval)
        total_prices_py = amounts_by_interval(starting.to_date.prev_year, ending.to_date.prev_year, interval)
        total_prices1 = total_prices.merge(total_prices_py)

        total_prices.map do |c, d|
            ly = 0
            total_prices_py.each do |e, f|
           
                if c.strftime("%m") == e.strftime("%m")
                    ly = f
                end
            end
            {date: c, total: d, total_ly: ly}
        end



        # total_prices.map do |a, b|
        #     {
        #         date: a,
        #         total: b || 0
        #     }
        # end
    end

    # this interval chart cannot supports multiple customer grouping. 
    def self.amounts_by_interval(starting, ending, interval)
        orders = joins(:line_items)
        orders = orders.where("invoices.c_date", starting.beginning_of_day..ending.beginning_of_day)
        orders = orders.where("account_id = 152")
        orders = orders.group("date_trunc('#{interval}', invoices.c_date)")
        orders = orders.order("invoices.c_date asc")
        orders = orders.select("date_trunc('#{interval}', invoices.c_date) as c_date, sum(line_items.homecurrency_amount) as subtotal")
        orders.each_with_object({}) do |order, prices|
            # binding.pry
            prices[order.c_date.to_date] = order.subtotal.round(2)
        end
    end




end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :authenticate_user!
    before_action :admin_only, except:[:show, :index]
    
    def create
        @item = Item.new(items_params)
        
        @item.save
        redirect_to @item
    end

    def show
        @item = Item.find(params[:id])
    end
    
    def new
        @item = Item.new
    end
    
    def index
        @item = Item.all
    end
    
    def edit
      @item = Item.find(params[:id])
    end
    
    def update
      @items = Item.find(params[:id])
      @items.update(items_params)
        redirect_to @items
    end

    
end

    private
        def items_params
            params.require(:item).permit(:name, :description, :code, :packsize, :qty, :unit)
    end

app/helpers/item_helper.rb
module ItemHelper
end

app/views/items/_newitemform.html.erb
<%= simple_form_for(@item) do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :code %>
    <%= f.input :packsize %>
    <%= f.input :qty %>
    <%= f.input :unit %>
    <%= f.button :submit %>
<% end %>

app/views/items/edit.html.erb
 <div id="page-wrapper" style="min-height: 629px;">
    <div class="row">
        <div class="col-lg-12">
            <h1><%= @item.name %></h1>
            <h3>ID:<%= @item.id %></h3>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <div class="order-right">
                <div class="form-group">
                    <label>Shipping Address</label>
            <%= simple_form_for @item, url: item_path do |f| %>
                <%= f.input :name, label: "Name", class: "form-control", placeholder: "Name", :maxlength => 41 %>
                <%= f.input :description, label: "Description", class: "form-control", placeholder: "Description", :maxlength => 96 %>
                <%= f.input :code, label: "Code", class: "form-control", placeholder: "Code", :maxlength => 41 %>
                <%= f.input :unit, label: "Unit", class: "form-control", placeholder: "Unit", :maxlength => 41 %>
            <%= f.submit "Save Changes" %>
            <% end %>
        </div>
    </div>
</div>

app/views/items/index.html.erb
 <div id="page-wrapper" style="min-height: 629px;">
    <div class="row">
        <div class="col-lg-12">
			<h1>Current Items</h1>
			<% @item.each do |item| %>  
			    <%= item.id %>.
			    <%= link_to item.name, item %> : <%= item.code %><br />
			<% end %>
		</div>
	</div>
</div>

app/views/items/new.html.erb
<h1>Enter A New Item</h1>
    <%= render partial: 'newitemform' %>

app/views/items/show.html.erb
 <div id="page-wrapper" style="min-height: 629px;">
    <div class="row">
        <div class="col-lg-12">
			<h1>Item Detail</h1>
			<span class="code">Code: <%= @item.code %><br /></span>
			<span class="code">UPC: <%= @item.upc %><br /></span>
			Name: <%= @item.name %><br />
			Description: <%= @item.description %><br />
			Unit: <%= @item.unit %><br />

			<p><%= link_to "Edit", edit_item_path %></p>
		</div>
	</div>
</div>